services:
  postgres:
    image: postgres:15
    container_name: payload-test
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres13_data:/var/lib/postgresql/data

volumes:
  postgres13_data:
